In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("car.data_target.csv")

In [3]:
df

buying     maint  doors persons lug_boot safety    target
0     veryhigh  veryhigh      2       2    small    low     unacc
1     veryhigh  veryhigh      2       2    small    med     unacc
2     veryhigh  veryhigh      2       2    small   high     unacc
3     veryhigh  veryhigh      2       2      med    low     unacc
4     veryhigh  veryhigh      2       2      med    med     unacc
...        ...       ...    ...     ...      ...    ...       ...
1723       low       low  5more    more      med    med      good
1724       low       low  5more    more      med   high  verygood
1725       low       low  5more    more      big    low     unacc
1726       low       low  5more    more      big    med      good
1727       low       low  5more    more      big   high  verygood

[1728 rows x 7 columns]

In [4]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'target'], dtype='object')

<ul>
    <li> buying : traducao</li>
    <li> maint </li>
    <li> doors</li>
    <li> persons</li>
    <li> lug_boot</li>
    <li> safety</li>
    <li> target</li>
    </ul>

In [5]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
target      0
dtype: int64

In [6]:
df_target = df.drop(['buying','maint','doors','persons','lug_boot','safety'], axis = 1)

In [7]:
df_target.sample(5)

target
832        acc
19       unacc
886      unacc
1697  verygood
272      unacc

In [8]:
df = df.drop(['target'], axis = 1)

In [9]:
df.sample(4)

buying maint  doors persons lug_boot safety
339   veryhigh   low      2       4      big    low
1580       low   med      4       4      med   high
1717       low   low  5more       4      big    med
176   veryhigh  high      4       4      med   high

In [10]:
np.unique(df['buying'], return_counts = True)

(array(['high', 'low', 'med', 'veryhigh'], dtype=object),
 array([432, 432, 432, 432]))

In [11]:
np.unique(df['maint'])

array(['high', 'low', 'med', 'veryhigh'], dtype=object)

In [12]:
np.unique(df['doors'], return_counts = True)

(array(['2', '3', '4', '5more'], dtype=object), array([432, 432, 432, 432]))

In [13]:
np.unique(df['persons'], return_counts = True)

(array(['2', '4', 'more'], dtype=object), array([576, 576, 576]))

In [14]:
np.unique(df['lug_boot'], return_counts = True)

(array(['big', 'med', 'small'], dtype=object), array([576, 576, 576]))

In [15]:
np.unique(df['safety'], return_counts = True)

(array(['high', 'low', 'med'], dtype=object), array([576, 576, 576]))

# Iniciando as funções

In [16]:
def tipo_buying(line):
    if line == 'low' :
        return '1'
    elif line == 'med':
        return '2'
    elif line == 'high' :
        return '3'
    else :
        return '4'

In [17]:
def tipo_maint(line):
    if line == 'high' :
        return '3'
    elif line == 'low' :
        return '1'
    elif line == 'med':
        return '2'
    else :
        return '4'

In [18]:
def tipo_doors(line):
    if line == '2' :
        return '1'
    elif line == '3' :
        return '2'
    elif line == '4':
        return '3'
    else :
        return '4'

In [19]:
def tipo_lug_boot(line):
    if line == 'big' :
        return '3'
    elif line == 'med' :
        return '2'
    elif line == 'small':
        return '1'
    else :
        return '0'

In [20]:
def tipo_persons(line):
    if line == '2' :
        return '1'
    elif line == '4' :
        return '2'
    else :
        return '3'

In [21]:
def tipo_doors(line):
    if line == '2' :
        return '1'
    elif line == '3' :
        return '2'
    elif line == '4':
        return '3'
    else :
        return '4'

In [22]:
def tipo_safety(line):
    if line == 'high' :
        return '3'
    elif line == 'low' :
        return '1'
    elif line == 'med':
        return '2'
    else :
        return '0'

In [23]:
df['buying']   = df['buying'].apply(lambda x: tipo_buying(x))
df['maint']    = df['maint'].apply(lambda x: tipo_maint(x))
df['doors']    = df['doors'].apply(lambda x: tipo_doors(x))
df['persons']  = df['persons'].apply(lambda x: tipo_persons(x))
df['safety']   = df['safety'].apply(lambda x: tipo_safety(x))
df['lug_boot'] = df['lug_boot'].apply(lambda x: tipo_safety(x))

In [24]:
df.head()

buying maint doors persons lug_boot safety
0      4     4     1       1        0      1
1      4     4     1       1        0      2
2      4     4     1       1        0      3
3      4     4     1       1        2      1
4      4     4     1       1        2      2

In [25]:
x = df

In [26]:
def target(line):
    if line == 'acc' :
        return '2'
    elif line == 'good' :
        return '3'
    elif line == 'unacc' :
        return '1'
    else :
        return '4'

In [27]:
df_target['target_'] = df_target['target'].apply(lambda x: target(x))

In [28]:
df_target.sample(5)

target target_
574   unacc       1
1266  unacc       1
73    unacc       1
936   unacc       1
1074  unacc       1

In [29]:
np.unique(df_target['target_'], return_counts = True)

(array(['1', '2', '3', '4'], dtype=object), array([1210,  384,   69,   65]))

In [30]:
np.unique(df_target['target'], return_counts = True)

(array(['acc', 'good', 'unacc', 'verygood'], dtype=object),
 array([ 384,   69, 1210,   65]))

In [31]:
df_target = df_target.drop(['target'],axis=1)

In [32]:
df_target.sample(5)

target_
149        1
804        1
151        1
1374       1
1234       2

In [33]:
y = df_target

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
from sklearn import preprocessing

In [36]:
min_max_scaler = preprocessing.MinMaxScaler()

In [37]:
x = min_max_scaler.fit_transform(x)

In [38]:
dfx = pd.DataFrame(x)

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [40]:
y_test

target_
295        2
22         1
814        1
297        1
1006       1
...      ...
1724       4
667        1
805        2
1706       1
573        1

[346 rows x 1 columns]

In [41]:
dfy_train = pd.DataFrame(y_train)

In [42]:
dfy_train.sample(5)

target_
945        1
1619       4
395        2
1218       1
231        1

In [43]:
y_train

target_
739        1
291        1
362        2
1283       4
718        2
...      ...
1033       1
721        1
253        1
1524       1
950        1

[1382 rows x 1 columns]

In [44]:
x_train

array([[0.66666667, 0.33333333, 1.        , 0.5       , 0.        ,
        0.5       ],
       [1.        , 0.33333333, 0.66666667, 1.        , 1.        ,
        0.        ],
       [1.        , 0.        , 0.33333333, 0.5       , 0.        ,
        1.        ],
       ...,
       [1.        , 0.33333333, 0.33333333, 0.5       , 0.        ,
        0.5       ],
       [0.        , 0.33333333, 0.        , 0.5       , 1.        ,
        0.        ],
       [0.33333333, 1.        , 1.        , 0.        , 1.        ,
        1.        ]])

In [45]:
x_test

array([[1.        , 0.33333333, 0.66666667, 1.        , 0.        ,
        0.5       ],
       [1.        , 1.        , 0.        , 1.        , 1.        ,
        0.5       ],
       [0.66666667, 0.        , 0.66666667, 0.        , 1.        ,
        0.5       ],
       ...,
       [0.66666667, 0.        , 0.33333333, 1.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 1.        , 0.        , 1.        ,
        1.        ],
       [0.66666667, 0.66666667, 0.33333333, 0.        , 0.        ,
        0.        ]])

In [46]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import svm

In [47]:
clf = svm.SVC()

In [48]:
clf.fit(x_train, y_train)

/home/temporary/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [49]:
y_pred = clf.predict(x_test)

In [50]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [51]:
accuracy_score(y_test, y_pred)

0.8786127167630058

In [52]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[224  17   0   2]
 [  3  65   4   4]
 [  0   6   4   6]
 [  0   0   0  11]]
              precision    recall  f1-score   support

           1       0.99      0.92      0.95       243
           2       0.74      0.86      0.79        76
           3       0.50      0.25      0.33        16
           4       0.48      1.00      0.65        11

    accuracy                           0.88       346
   macro avg       0.68      0.76      0.68       346
weighted avg       0.89      0.88      0.88       346



In [56]:
clf_precomputed = svm.SVC(kernel='precomputed')

In [57]:
gram_train = np.dot(x_train, x_train.T)

In [58]:
clf_precomputed.fit(gram_train, y_train)

/home/temporary/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='precomputed')

In [59]:
gram_test = np.dot(x_test, x_train.T)

In [60]:
y_pred = clf_precomputed.predict(gram_test)

In [61]:
accuracy_score(y_test, y_pred)

0.8236994219653179

In [62]:
import pickle

In [63]:
# save the model to disk
filename = 'car_model.sav'
pickle.dump(clf, open(filename, 'wb'))